"""Audit-domain enums: verdicts, status codes, warning codes, and lookup tables."""

from __future__ import annotations

import enum
from collections.abc import Mapping

from datp.core.metric_enums import MetricName


class AuditStatus(enum.StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    MISSING = "MISSING"
    PARTIAL = "PARTIAL"
    BLOCKED_PENDING_RUN = "BLOCKED_PENDING_RUN"
    WARNING = "WARNING"


class InvariantField(enum.StrEnum):
    """Hash fields and violation labels checked by the B1–B4 shared-training invariant."""

    SPLIT_HASH = "split_hash"
    MODEL_HASH = "model_hash"
    ENCODER_HASH = "encoder_hash"
    SCORING_CODE_HASH = "scoring_code_hash"
    METRICS_CODE_HASH = "metrics_code_hash"
    MODEL_OR_ENCODER_HASH = "model_hash_or_encoder_hash"
    RECONSTRUCTION_ERROR_ARRAYS = "reconstruction_error_arrays"


class ReuseVerdict(enum.StrEnum):
    VERIFIED_REUSE_SAFE = "VERIFIED_REUSE_SAFE"
    REUSE_BLOCKED_RERUN_REQUIRED = "REUSE_BLOCKED_RERUN_REQUIRED"


class WarningCode(enum.StrEnum):
    B0_AUROC_BELOW_THRESHOLD = "B0_AUROC_BELOW_THRESHOLD"
    B0_NORMALIZATION_DIAGNOSTIC_BLOCKED = "B0_NORMALIZATION_DIAGNOSTIC_BLOCKED"
    B0_SANITY_LOW_AUROC = "B0_SANITY_LOW_AUROC"
    B0_SANITY_LOW_PR_AUC = "B0_SANITY_LOW_PR_AUC"
    B0_SANITY_PR_AUC_PENDING = "B0_SANITY_PR_AUC_PENDING"
    B0_WEAK_AUC_BLOCKS_PAPER = "B0_WEAK_AUC_BLOCKS_PAPER"
    B1_NOT_POOLED_PERCENTILE = "B1_NOT_POOLED_PERCENTILE"
    B1_MEAN_NOT_POOLED_PERCENTILE = "B1_MEAN_NOT_POOLED_PERCENTILE"
    B2_UTILITY_TRADEOFF = "B2_UTILITY_TRADEOFF"
    B3_TAXONOMY_TOO_COARSE = "B3_TAXONOMY_TOO_COARSE"
    B4_CLUSTER_DIAGNOSTICS_INCOMPLETE = "B4_CLUSTER_DIAGNOSTICS_INCOMPLETE"
    B4_SINGLE_CLUSTER = "B4_SINGLE_CLUSTER"
    CAL_PENDING_HIGH_FRACTION = "CAL_PENDING_HIGH_FRACTION"
    CICIOT_HOMOGENEITY_BLOCKED = "CICIOT_HOMOGENEITY_BLOCKED"
    CICIOT_HOMOGENEITY_INCOMPLETE = "CICIOT_HOMOGENEITY_INCOMPLETE"
    CICIOT_HOMOGENEITY_VERIFIED = "CICIOT_HOMOGENEITY_VERIFIED"
    CICIOT_HETEROGENEITY_DETECTED = "CICIOT_HETEROGENEITY_DETECTED"
    CICIOT_NOT_HOMOGENEOUS = "CICIOT_NOT_HOMOGENEOUS"
    CLUSTER_THRESHOLD_RECONSTRUCTION_FAILED = "CLUSTER_THRESHOLD_RECONSTRUCTION_FAILED"
    CONVERGENCE_NOT_REACHED = "CONVERGENCE_NOT_REACHED"
    COVERAGE_BELOW_THRESHOLD = "COVERAGE_BELOW_THRESHOLD"
    FIXED_OPERATING_POINT_METRICS_PENDING = "FIXED_OPERATING_POINT_METRICS_PENDING"
    FLAT_CV_TPR_SUSPICIOUS = "FLAT_CV_TPR_SUSPICIOUS"
    MISSING_CONVERGENCE_CURVES = "MISSING_CONVERGENCE_CURVES"
    MISSING_CONFUSION_MATRICES = "MISSING_CONFUSION_MATRICES"
    MISSING_CONFUSION_MATRIX = "MISSING_CONFUSION_MATRIX"
    MISSING_PARTITION_MANIFEST = "MISSING_PARTITION_MANIFEST"
    MISSING_RUN = "MISSING_RUN"
    MISSING_SCORE_ARTIFACTS = "MISSING_SCORE_ARTIFACTS"
    METRIC_DENOMINATOR_MISMATCH = "METRIC_DENOMINATOR_MISMATCH"
    NAKED_CV_FPR = "NAKED_CV_FPR"
    PRIMARY_DELTA_INCOMPLETE = "PRIMARY_DELTA_INCOMPLETE"
    NO_COMPLETED_RESULTS = "NO_COMPLETED_RESULTS"
    REGIME_C_ALPHA_AUDIT_MISSING = "REGIME_C_ALPHA_AUDIT_MISSING"
    REGIME_C_PREPARED_MANIFEST_MISSING = "REGIME_C_PREPARED_MANIFEST_MISSING"
    SCHEMA_VERSION_MISMATCH = "SCHEMA_VERSION_MISMATCH"
    STABLE_WORST_CLIENT = "STABLE_WORST_CLIENT"
    THRESHOLD_RECONSTRUCTION_FAILED = "THRESHOLD_RECONSTRUCTION_FAILED"
    WORST_CLIENT_STABLE = "WORST_CLIENT_STABLE"
    WORST_CLIENT_VARIES = "WORST_CLIENT_VARIES"


class AuditSeverity(enum.StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    FAIL = "FAIL"
    MISSING = "MISSING"
    PARTIAL = "PARTIAL"
    BLOCKED_PENDING_RUN = "BLOCKED_PENDING_RUN"


class DenominatorStatus(enum.StrEnum):
    """Status for metric denominator checks; also used for per-attack metric status."""

    PASS = "PASS"
    FAIL = "FAIL"
    EXCLUDED_EVALUATION_INCOMPLETE = "EXCLUDED_EVALUATION_INCOMPLETE"
    BLOCKED_PENDING_RUN = "BLOCKED_PENDING_RUN"


class HomogeneityVerdict(enum.StrEnum):
    HOMOGENEOUS = "HOMOGENEOUS"
    HETEROGENEOUS = "HETEROGENEOUS"
    BLOCKED_PENDING_RUN = "BLOCKED_PENDING_RUN"


class SeverityTrendStatus(enum.StrEnum):
    SIGNIFICANT = "SIGNIFICANT"
    NOT_SIGNIFICANT = "NOT_SIGNIFICANT"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class SeverityVariable(enum.StrEnum):
    DEVICE_MIXTURE_JS_MEAN = "device_mixture_js_mean"
    RECON_ERROR_JS_MEAN = "recon_error_js_mean"
    ALPHA_NUMERIC = "alpha_numeric"


class OutcomeVariable(enum.StrEnum):
    DELTA_B1_B2 = "delta_b1_b2"


class WorstDirection(enum.StrEnum):
    MAX_IS_WORST = "max_is_worst"
    MIN_IS_WORST = "min_is_worst"


WORST_CLIENT_DIRECTIONS: Mapping[MetricName, WorstDirection] = {
    MetricName.FPR: WorstDirection.MAX_IS_WORST,
    MetricName.TPR: WorstDirection.MIN_IS_WORST,
    MetricName.MACRO_F1: WorstDirection.MIN_IS_WORST,
    MetricName.BALANCED_ACCURACY: WorstDirection.MIN_IS_WORST,
}
