from collections.abc import Iterable
from collections.abc import Callable
from os import PathLike
from typing import Any, Generic, ParamSpec, TypeVar

P = ParamSpec("P")
R = TypeVar("R")

class _DelayedCall(Generic[R]): ...

class Parallel:
    def __init__(self, n_jobs: int | None = ..., **kwargs: Any) -> None: ...
    def __call__(self, tasks: Iterable[_DelayedCall[R]]) -> list[R]: ...

def delayed(function: Callable[P, R]) -> Callable[P, _DelayedCall[R]]: ...
def dump(value: object, filename: str | PathLike[str], **kwargs: Any) -> list[str]: ...
def load(filename: str | PathLike[str], **kwargs: Any) -> Any: ...
