from numpy.typing import ArrayLike

def adjusted_rand_score(labels_true: ArrayLike, labels_pred: ArrayLike) -> float: ...
def average_precision_score(y_true: ArrayLike, y_score: ArrayLike, **kwargs: object) -> float: ...
def roc_auc_score(y_true: ArrayLike, y_score: ArrayLike, **kwargs: object) -> float: ...
def silhouette_score(X: ArrayLike, labels: ArrayLike, **kwargs: object) -> float: ...
