# Cliff's delta magnitude boundaries (Romano et al., 2006, Table 1).
DEFAULT_CI_LEVEL: float = 0.95
BOOTSTRAP_RANDOM_STATE: int = 42

CLIFFS_DELTA_NEGLIGIBLE = 0.147
CLIFFS_DELTA_SMALL = 0.33
CLIFFS_DELTA_MEDIUM = 0.474

EXTREME_PERCENTILE = 95
JS_LAPLACE_SMOOTHING = 1e-12
JS_BIN_EPSILON = 1e-9
